name: Тесты library_app
on: [push]
jobs:
  container-job:
    name: Тесты
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DBNAME: postgres
          POSTGRES_USER: test
          POSTGRES_PORT: 5432
          POSTGRES_HOST: 127.0.0.1
        ports:
        - 5432:5432
      minio:
        image: minio/minio
        env:
          MINIO_ROOT_USER: user
          MINIO_ROOT_PASSWORD: password
        ports:
        - 9000:9000
        - 9001:9001
        options: server /data --console-address ":9001"
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.12"
    - name: Установка модулей и зависимостей
      run: |
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        pip install GDAL==3.6.4
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    - name: Тесты api
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_api