# Generated by Django 5.0.3 on 2024-05-03 00:40

import django.db.models.deletion
import manager.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone_number', models.CharField(max_length=12, validators=[manager.models.phone_number_validator], verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'agency',
                'verbose_name_plural': 'agencies',
                'db_table': '"tours_data"."agency"',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.agency', verbose_name='agency')),
            ],
            options={
                'verbose_name': 'tour',
                'verbose_name_plural': 'tours',
                'db_table': '"tours_data"."tour"',
                'ordering': ['name'],
                'unique_together': {('name', 'description', 'agency')},
            },
        ),
    ]
