# Generated by Django 5.0.3 on 2024-05-03 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_agency_address_alter_address_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.FloatField(verbose_name='rating')),
                ('text', models.TextField(blank=True, max_length=8192, null=True, verbose_name='text')),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.agency', verbose_name='agencies')),
            ],
            options={
                'db_table': '"tours_data"."review"',
            },
        ),
    ]
