# Generated by Django 5.0.3 on 2024-05-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_remove_review_agency_id_review_agency_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        # migrations.AlterUniqueTogether(
        #     name='address',
        #     unique_together={('city', 'street', 'house_number', 'entrance_number', 'floor', 'flat_number')},
        # ),
    ]
