# Generated by Django 5.0.3 on 2024-05-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_address_options_alter_address_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('agency', 'account')},
        ),
    ]
