# Generated by Django 5.0.3 on 2024-05-04 01:14

import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_country_name'),
    ]

    operations = [
        CreateExtension("postgis"),
        migrations.AddField(
            model_name='city',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326, verbose_name='city geopoint'),
            preserve_default=False,
        ),
    ]
