# Generated by Django 4.2.4 on 2024-05-05 20:10

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0014_address_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='city',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True, verbose_name='city geopoint'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('city', 'street', 'house_number', 'entrance_number', 'floor', 'flat_number', 'point')},
        ),
    ]
