# Generated by Django 4.2.4 on 2024-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_account_account_alter_city_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_agency',
            field=models.BooleanField(default=None, verbose_name='agency account'),
            preserve_default=False,
        ),
    ]
