# Generated by Django 4.1.7 on 2024-05-22 22:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'relationship tour country',
                'verbose_name_plural': 'relationships tour country',
                'db_table': '"tours_data"."tour_country"',
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='tours',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='cities',
        ),
        migrations.AddField(
            model_name='tour',
            name='starting_city',
            field=models.ForeignKey(default='da707b24-d4ce-48dd-bb31-28bc8feabb53', on_delete=django.db.models.deletion.CASCADE, to='manager.city', verbose_name='starting city'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TourCity',
        ),
        migrations.AddField(
            model_name='tourcountry',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.tour', verbose_name='tour'),
        ),
        migrations.AddField(
            model_name='country',
            name='tours',
            field=models.ManyToManyField(through='manager.TourCountry', to='manager.tour', verbose_name='tours'),
        ),
        migrations.AddField(
            model_name='tour',
            name='countries',
            field=models.ManyToManyField(through='manager.TourCountry', to='manager.country', verbose_name='country'),
        ),
        migrations.AlterUniqueTogether(
            name='tourcountry',
            unique_together={('tour', 'country')},
        ),
    ]
