# Generated by Django 4.1.7 on 2024-05-23 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_tourcountry_remove_city_tours_remove_tour_cities_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(default='ff2cf79f-9db0-4e3d-b7e0-f5a985d68d7d', on_delete=django.db.models.deletion.CASCADE, to='manager.tour', verbose_name='tour'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('tour', 'account')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='agency',
        ),
    ]
