# Generated by Django 4.1.7 on 2024-05-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_alter_review_unique_together_review_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=9, verbose_name='price'),
            preserve_default=False,
        ),
    ]
