# Generated by Django 4.1.7 on 2024-05-23 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_tour_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.address', verbose_name='address')),
            ],
            options={
                'verbose_name': 'relationship tour address',
                'verbose_name_plural': 'relationships tour address',
                'db_table': '"tours_data"."tour_address"',
            },
        ),
        migrations.RemoveField(
            model_name='country',
            name='tours',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='countries',
        ),
        migrations.DeleteModel(
            name='TourCountry',
        ),
        migrations.AddField(
            model_name='touraddress',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.tour', verbose_name='tour'),
        ),
        migrations.AddField(
            model_name='address',
            name='tours',
            field=models.ManyToManyField(through='manager.TourAddress', to='manager.tour', verbose_name='tours'),
        ),
        migrations.AddField(
            model_name='tour',
            name='addresses',
            field=models.ManyToManyField(through='manager.TourAddress', to='manager.address', verbose_name='address'),
        ),
        migrations.AlterUniqueTogether(
            name='touraddress',
            unique_together={('tour', 'address')},
        ),
    ]
