# Generated by Django 4.1.7 on 2024-05-24 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_touraddress_remove_country_tours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_agency',
        ),
        migrations.AddField(
            model_name='account',
            name='agency',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.agency', verbose_name='agency account'),
        ),
    ]
