# Generated by Django 4.1.7 on 2024-05-27 11:07

from django.db import migrations, models
import manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_alter_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=manager.validators.get_datetime, validators=[manager.validators.date_validator], verbose_name='creatin date and time'),
        ),
    ]
