# Generated by Django 4.1.7 on 2024-05-28 01:35

from django.db import migrations, models
import manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_alter_review_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='edited',
            field=models.DateTimeField(blank=True, default=None, null=True, validators=[manager.validators.date_validator], verbose_name='last edit date and time'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=manager.validators.get_datetime, validators=[manager.validators.date_validator], verbose_name='creation date and time'),
        ),
    ]
