# Generated by Django 4.1.7 on 2024-05-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_review_edited_alter_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(verbose_name='rating'),
        ),
    ]
