# Generated by Django 4.2.4 on 2024-06-16 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0033_agencyrequests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agencyrequests",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request",
                to="manager.account",
                verbose_name="account",
            ),
        ),
        migrations.AlterField(
            model_name="agencyrequests",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request",
                to="manager.agency",
                verbose_name="agency",
            ),
        ),
    ]
